### ISSUE TITLE
Drinking anything that gives nausea causes a crash, potentially could corrupt world

### ISSUE THREAD

**Issue by darthvader45** [rwtema/modjam2018#15]
Apparently drinking anything like potions or liquor that gives the nausea effect to simulate being drunk crashes, because the monk healing power that purges the body of toxins can't recognize it.  Maybe have the ability recognize more negative potion effects, including compat for mods?

**Comment by CplPibald** [comment]
Do you have a crash log?

**Comment by darthvader45** [comment]
Here it is:
https://paste.dimdev.org/abejufefid.sql

**Comment by darthvader45** [comment]
I was drinking Millenaire cider when this happened.  Just wanted to celebrate with the Alchemist, and this is how the game repays me.

**Comment by darthvader45** [comment]
Alrighty, now all that's left is the level 20 bug and I'll be just fine.  Thank you, @rwtema, you are a godsend.
